services:


  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"
  
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - 80:80

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    ports:
      - 81:80
